apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Three tier
  namespace: workshop
spec:
  project: default

  source:
    repoURL: https://github.com/singareddy88/Three-tier-app.git
    targetRevision: HEAD
    path: k8s_manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: Three tier

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
