apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace : ingress-nginx
spec:
  selector:
    app: threetier

  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
